services:
  firefox:
    container_name: firefox
    image: lscr.io/linuxserver/firefox:latest
    restart: unless-stopped
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - /docker/firefox:/config
      - /safe/firefox:/downloads
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [compute,video,graphics,utility]
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Calcutta
      - DRINODE=/dev/dri/renderD128
      - CUSTOM_USER=${CUSTOM_USER}
      - PASSWORD=${PASSWORD}
    shm_size: "1gb"
