---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/docker/

# my-docker:
#   host: 127.0.0.1
#   port: 2375

safe:
    host: 192.168.1.199
    port: 2375
apps:
    host: 192.168.1.201
    port: 2375
network:
    host: 192.168.1.101
    port: 2375
