---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- search:
    provider: google
    # focus: true
    showSearchSuggestions: true
    target: _blank
- openmeteo:
    label: PVR
    latitude: 17.38405
    longitude: 78.45636
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1
- datetime:
    format:
        timeStyle: medium
        # dateStyle: long
        hourCycle: h24
- resources:
    cpu: true
    memory: true
    cputemp: true
    tempmin: 0 # optional, minimum cpu temp
    tempmax: 100 # optional, maximum cpu temp
    # uptime: true
    units: metric # only used by cpu temp, options: 'imperial' or 'metric'
    refresh: 3000 # optional, in ms
    diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
    # network: true # optional, uses 'default' if true or specify a network interface name
