services:
  ollama:
    container_name: ollama
    image: ollama/ollama:0.5.7
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - /docker/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:0.5.7
    restart: always
    environment:
      BYPASS_MODEL_ACCESS_CONTROL: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3009:8080"
    volumes:
      - /docker/openwebui:/app/backend/data
