services:
  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      OPENAI_API_KEY: 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
      DATA_DIR: /data
    volumes:
      - /docker/hoarder/data:/data
    ports:
      - 3500:3000
    env_file:
      - stack.env
    restart: unless-stopped

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data
    env_file:
      - stack.env
    restart: unless-stopped

volumes:
  meilisearch:
