services:
  # jellyfin:
  #   container_name: jellyfin
  #   image: jellyfin/jellyfin
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Asia/Calcutta
  #   volumes:
  #     - /docker/jellyfin:/config
  #     - /data:/data
  #   ports:
  #     - 8096:8096
  #   devices:
  #     - /dev/dri:/dev/dri # QuickSync
  #   restart: unless-stopped

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    restart: unless-stopped
    ports:
      - 5055:5055
    volumes:
      - /docker/jellyseerr:/app/config
    environment:
      - PUID=1000
      - PGID=10000
      - TZ=Asia/Calcutta

  jellystat-db:
    container_name: jellystat-db
    image: postgres:15.2
    restart: unless-stopped
    volumes:
      - /docker/jellyfin/stats/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword

  jellystat:
    container_name: jellystat
    image: cyfershepard/jellystat:latest
    restart: unless-stopped
    ports:
      - 3001:3000
    volumes:
      - /docker/jellyfin/stats/backup-data:/app/backend/backup-data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: 397ce4ab6e324247a8f66de61eb75fde
      TZ: Asia/Calcutta
    depends_on:
      - jellystat-db
