services:
  couchdb:
    container_name: obsidian-couchdb
    image: couchdb
    restart: always
    environment:
      - COUCHDB_USER=priyesh
      - COUCHDB_PASSWORD={password}
    volumes:
      - /docker/obsidian/couchdb-data:/opt/couchdb/data
      - /docker/obsidian/couchdb-etc:/opt/couchdb/etc/local.d
    ports:
      - 5984:5984
