services:
  stirling-pdf:
    container_name: stirling-pdf
    image: stirlingtools/stirling-pdf:latest
    ports:
      - 8081:8080
    restart: unless-stopped
    volumes:
      - ./trainingData:/usr/share/tessdata # Required for extra OCR languages
      - /docker/stirlingpdf:/config
    #      - ./customFiles:/customFiles/
    #      - ./logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
