# Compose file for the *arr stack. Configuration files are stored
# in a docker folder mounted in root. Change to bind mounts if needed.
# All containers are ran with user and group ids of the main user and
# share to aviod permissions issues of downloaded files, please refer
# the read me file for more information.
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - 8080:8080
      - 6881:6881
    volumes:
      - /docker/qbittorrent:/config
      - /data:/data
      # - /data2:/data2
    environment:
      - PUID=1000
      - PGID=10000
      - TZ=Asia/Calcutta
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881

  nzbget:
    image: ghcr.io/linuxserver/nzbget:latest
    container_name: nzbget
    restart: unless-stopped
    ports:
      - 6789:6789
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/nzbget:/config
      - /data:/data
      # - /data2:/data2
    environment:
      - PUID=1000
      - PGID=10000
      - TZ=Asia/Calcutta
      - NZBGET_USER=priyesh
      - NZBGET_PASS=itwasmeDIO!

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - 9696:9696
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/prowlarr:/config
    environment:
      - PUID=1000
      - PGID=10000
      - TZ=Asia/Calcutta

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    ports:
      - "${PORT:-8191}:8191"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Asia/Calcutta

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/sonarr:/config
      - /data:/data
      # - /data2:/data2
    environment:
      - PUID=1000
      - PGID=10000
      - UMASK=002
      - TZ=Asia/Calcutta

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/radarr:/config
      - /data:/data
      # - /data2:/data2
    environment:
      - PUID=1000
      - PGID=10000
      - TZ=Asia/Calcutta

  lidarr:
    container_name: lidarr
    image: ghcr.io/linuxserver/lidarr:latest
    restart: unless-stopped
    ports:
      - 8686:8686
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/lidarr:/config
      - /data:/data
      # - /data2:/data2
    environment:
      - PUID=1000
      - PGID=10000
      - TZ=Asia/Calcutta

  bazarr:
    image: ghcr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    ports:
      - 6767:6767
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/bazarr:/config
      - /data:/data
      # - /data2:/data2
    environment:
      - PUID=1000
      - PGID=10000
      - TZ=Asia/Calcutta

  # readarr:
  #   image: ghcr.io/linuxserver/readarr:latest
  #   container_name: readarr
  #   restart: unless-stopped
  #   ports:
  #     - 8787:8787
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /docker/readarr:/config
  #     - /data:/data
  #     # - /data2:/data2
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Asia/Calcutta
