# Compose file for the *arr stack. Configuration files are stored
# in a docker folder mounted in root. Change to bind mounts if needed.
# All containers are ran with user and group ids of the main user and
# share to aviod permissions issues of downloaded files, please refer
# the read me file for more information.
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Calcutta
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /docker/qbittorrent:/config
      - /data:/data
      - /data2:/data2
    ports:
      - 8080:8080
      - 6881:6881
    restart: unless-stopped

  nzbget:
    image: ghcr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Calcutta
      - NZBGET_USER=priyesh
      - NZBGET_PASS=itwasmeDIO!
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/nzbget:/config
      - /data:/data
      - /data2:/data2
    ports:
      - 6789:6789
    restart: unless-stopped

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Calcutta
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Asia/Calcutta
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Calcutta
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/sonarr:/config
      - /data:/data
      - /data2:/data2
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Calcutta
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/radarr:/config
      - /data:/data
      - /data2:/data2
    ports:
      - 7878:7878
    restart: unless-stopped

  lidarr:
    container_name: lidarr
    image: ghcr.io/linuxserver/lidarr:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/lidarr:/config
      - /data:/data
      - /data2:/data2
    environment:
      - PUID=1000
      - PGID=1000
        - TZ=Asia/Calcutta
    ports:
      - 8686:8686
    restart: unless-stopped

  bazarr:
    image: ghcr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Calcutta
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/bazarr:/config
      - /data:/data
      - /data2:/data2
    ports:
      - 6767:6767
    restart: unless-stopped

  readarr:
    image: ghcr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Calcutta
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/readarr:/config
      - /data:/data
      - /data2:/data2
    ports:
      - 8787:8787
    restart: unless-stopped
