services:
  db_recipes:
    container_name: tandoor_db_recipes
    restart: unless-stopped
    image: postgres:16-alpine
    volumes:
      - /docker/tandoor/postgresql:/var/lib/postgresql/data

  web_recipes:
    container_name: tandoor_web_recipes
    image: vabene1111/recipes
    restart: unless-stopped
    volumes:
      - /docker/tandoor/staticfiles:/opt/recipes/staticfiles
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - /docker/tandoor/nginx_config:/opt/recipes/nginx/conf.d
      - /docker/tandoor/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes

  nginx_recipes:
    container_name: tandoor_nginx_recipes
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 8888:80
    depends_on:
      - web_recipes
    volumes:
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - /docker/tandoor/nginx_config:/etc/nginx/conf.d:ro
      - /docker/tandoor/staticfiles:/static:ro
      - /docker/tandoor/mediafiles:/media:ro

